var cranes = [
{id: 'Shipping/Receiving', type: 'Toolbox', status: false},
{id: '01-Mill', type: 'Toolbox', status: false},
{id: '02-Floors', type: 'Toolbox', status: false},
{id: '03-Prefab', type: 'Toolbox', status: false},
{id: '04-Walls1', type: 'Toolbox', status: false},
{id: '05-Walls2', type: 'Toolbox', status: false},
{id: '06-Setup', type: 'Toolbox', status: false},
{id: '07-Roofs', type: 'Toolbox', status: false},
{id: '09-FinalFinish', type: 'Toolbox', status: false},
{id: '1A05-Plumbing', type: 'Toolbox', status: false},
{id: '1A06-Skinning', type: 'Toolbox', status: false},
{id: '1A08-HVAC', type: 'Toolbox', status: false},
{id: 'A3110501', type: 'Crane Inspection', status: false },
{id: 'AS-01-001-10B', type: 'Crane Inspection', status: false },
{id: 'AS-01-001-11B', type: 'Crane Inspection', status: false },
{id: 'AS-01-001-9B', type: 'Crane Inspection', status: false },
{id: 'AS-01-002-6B', type: 'Crane Inspection', status: false },
{id: 'AS-01-002-7B', type: 'Crane Inspection', status: false },
{id: 'AS-01-002-8B', type: 'Crane Inspection', status: false },
{id: 'AS-01-003-41', type: 'Crane Inspection', status: false },
{id: 'AS-01-003-42', type: 'Crane Inspection', status: false },
{id: 'AS-01-003-4B', type: 'Crane Inspection', status: false },
{id: 'AS-01-003-5B', type: 'Crane Inspection', status: false },
{id: 'AS-01-004-04&4B', type: 'Crane Inspection', status: false },
{id: 'AS-01-004-1B', type: 'Crane Inspection', status: false },
{id: 'AS-01-004-2B', type: 'Crane Inspection', status: false },
{id: 'AS-01-004-3B', type: 'Crane Inspection', status: false },
{id: 'AS-01-004-44', type: 'Crane Inspection', status: false },
{id: 'AS-01-005-45&46', type: 'Crane Inspection', status: false },
{id: 'AS-01-005-46&47', type: 'Crane Inspection', status: false },
{id: 'AS-01-005-05&45', type: 'Crane Inspection', status: false },
{id: 'AS-01-006-07', type: 'Crane Inspection', status: false },
{id: 'AS-01-006-08', type: 'Crane Inspection', status: false },
{id: 'AS-01-007-14', type: 'Crane Inspection', status: false },
{id: 'AS-01-007-15', type: 'Crane Inspection', status: false },
{id: 'AS-01-008-16', type: 'Crane Inspection', status: false },
{id: 'AS-01-008-17', type: 'Crane Inspection', status: false },
{id: 'AS-01-008-18', type: 'Crane Inspection', status: false },
{id: 'AS-01-009-21', type: 'Crane Inspection', status: false },
{id: 'AS-01-009-22', type: 'Crane Inspection', status: false },
{id: 'AS-01-009-23', type: 'Crane Inspection', status: false },
{id: 'AS-01-009-24', type: 'Crane Inspection', status: false },
{id: '1', type: 'Carrier Inspection', status: false },
{id: '2', type: 'Carrier Inspection', status: false },
{id: '3', type: 'Carrier Inspection', status: false },
{id: '4', type: 'Carrier Inspection', status: false },
{id: '5', type: 'Carrier Inspection', status: false },
{id: '6', type: 'Carrier Inspection', status: false },
{id: '7', type: 'Carrier Inspection', status: false },
{id: '8', type: 'Carrier Inspection', status: false },
{id: 'FL107', type: 'Forklift Inspection', status: false },
{id: 'FL108', type: 'Forklift Inspection', status: false },
{id: 'FL109', type: 'Forklift Inspection', status: false },
{id: 'FL114', type: 'Forklift Inspection', status: false },
{id: 'FL115', type: 'Forklift Inspection', status: false },
{id: 'FL116', type: 'Forklift Inspection', status: false },
{id: 'FL117', type: 'Forklift Inspection', status: false },
{id: 'FL118', type: 'Forklift Inspection', status: false },
{id: 'FL666', type: 'Forklift Inspection', status: false },
{id: 'FL-H1', type: 'Forklift Inspection', status: false },
{id: 'FL-H2', type: 'Forklift Inspection', status: false },
{id: 'ET-F-06-14984', type: 'Forklift Inspection', status: false },
{id: 'ET-F-06-15255', type: 'Forklift Inspection', status: false },
{id: 'B233N02696H', type: 'Power Pallet Inspection', status: false },
{id: 'A233N03080D', type: 'Power Pallet Inspection', status: false },
{id: 'A233N03074D', type: 'Power Pallet Inspection', status: false },
{id: 'GS3006A-085543', type: 'Scissor Lift Inspection', status: false },
{id: '0200183464', type: 'Scissor Lift Inspection', status: false },
{id: '0200186606', type: 'Scissor Lift Inspection', status: false },
{id: 'GS3013A-126605', type: 'Scissor Lift Inspection', status: false },
{id: 'GS3014A-128710', type: 'Scissor Lift Inspection', status: false },
];

module.exports = {cranes};
